#!/bin/sh

# Mount special filesystems
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

# Load the e1000 ethernet driver
# FIXME this is very hacky
insmod /e1000.ko.xz

# Setup networking
#ip link set eth0 up
#ip addr add 10.0.2.15 dev eth0
#ip route add 10.0.2.0/24 dev eth0
echo "10.0.2.2 host" > /etc/hosts

# Command disection:
# * `setsid` to run in a new session
# * `cttyhack` to allocate a controlling tty
# * `sh` to start an interactive shell
setsid cttyhack sh

# Reboot
echo b > /proc/sysrq-trigger
