load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Rules rust
http_archive(
    name = "io_bazel_rules_rust",
    sha256 = "c82118824b2448b77146f1dae97b6eaa717babedad0822aca4879f3cbbf2b7b5",
    strip_prefix = "rules_rust-3228ccd3814c2ad0d7307d2f87fb8ff9616149d7",
    urls = [
        # Master branch as of 2018-12-11
        "https://github.com/bazelbuild/rules_rust/archive/3228ccd3814c2ad0d7307d2f87fb8ff9616149d7.tar.gz",
    ],
)

http_archive(
    name = "bazel_skylib",
    sha256 = "eb5c57e4c12e68c0c20bc774bfbc60a568e800d025557bc4ea022c6479acc867",
    strip_prefix = "bazel-skylib-0.6.0",
    url = "https://github.com/bazelbuild/bazel-skylib/archive/0.6.0.tar.gz",
)

load("@io_bazel_rules_rust//:workspace.bzl", "bazel_version")

bazel_version(name = "bazel_version")

local_repository(
    name = "minimal_linux_bazel",
    path = "../",
)

# minimal linux bazel dependencies
load("@minimal_linux_bazel//:fetch.bzl", "fetch_dependencies")

fetch_dependencies()

http_archive(
    name = "raspberrypi_firmware",
    build_file_content = """ 
filegroup(
    name = "boot_files",
    srcs = glob(["boot/*"], exclude = ["boot/overlays"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "overlays",
    srcs = glob(["boot/overlays/**/*"]),
    visibility = ["//visibility:public"],
)

genrule(
    name = "rpi2-qemu-files",
    srcs = ["boot/kernel7.img", "boot/bcm2709-rpi-2-b.dtb"],
    visibility = ["//visibility:public"],
    outs = ["kernel7.img", "rpi2.dtb"],
    cmd = "cp $(location boot/kernel7.img) $(location kernel7.img) && \
         cp $(location boot/bcm2709-rpi-2-b.dtb) $(location rpi2.dtb)",
)
    """,
    sha256 = "6b6db5f15c400bc1224266fd44238dd9b2479fd09f8a55e36ccdac2120632f8f",
    strip_prefix = "firmware-1.20190215",
    url = "https://github.com/raspberrypi/firmware/archive/1.20190215.tar.gz",
)
